### PR TITLE
Rename CopyDLL to DeployDLL

### PR DESCRIPTION
**Pull request by alcesleo**
This slightly better reflects what it does since it also builds and generates documentation etc. Could give slight backwards incompatibility issues since the json-config key is also changed, I'm not sure how much we use that but it should be trivial to change.

### CODE REVIEW

**Comment by marcusl** [comment]
Since this renames a value in arasdb.json, users have to update it manually.

Should we implement a migration step for that?

**Comment by alcesleo** [comment]
Possibly, it's a really minor breaking change with a trivial fix but it could be easily forgotten. Maybe add a warning/error if the CopyDLL key is present in the json?

**Comment by marcusl** [comment]
Sounds good. Something like "deprecated key detect, plz remove or rename".

**Comment by alcesleo** [comment]
Actually you'd already get "No DeployDll section found in arasdb(-local).json" if it's missing, maybe this is enough

**Comment by marcusl** [comment]
Good enough probably

**Pull request merged**
